### ISSUE TITLE
Протокол обмена данными не специфицирован

### ISSUE THREAD

**Issue by vani2** [Beeline-Digital/api.beeline.ru#6]
Не специфицированы допустимые и необходимые поля заголовка запроса. 
В том числе не описано в каком виде передается ключ сессии.

**Comment by NataBoginia** [comment]
Добавлен раздел с описанием заголовков http://beeline-digital.github.io/api.beeline.ru/apispec/selfservice.html#%D0%BE%D0%B1%D1%8F%D0%B7%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%B7%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BA%D0%B8
