### ISSUE TITLE
Нарушена семантики запроса

### ISSUE THREAD

**Issue by vani2** [Beeline-Digital/api.beeline.ru#7]
Запрос `POST /mobapp/tips/{ctn}/{id}` - Скрытие пользовательского контекста, тогда как отключение услуги, удаление номера SSO реализовано через DELETE.
Так же последовательность сущностей, например, в запросе `/selfservice/ctn/{ctn}/subscriptions/{id}` ctn-subscribtions с указанием идентификаторов, тогда как в этом запросе нет указания сущности ctn, идентификатор tip следует за идентификатором ctn.
Подобное поведение также замечено в методе `POST/selfservice/ctn/{ctn}/tps/mobile/{soc}`

**Comment by SuperCuke** [comment]
Не понял в чем проблема.

POST /mobapp/tips/{ctn}/{id} - Мы **не удаляем** tip, мы помечаем tip как просмотренный. Нет факта удаления объекта, непонятно зачем ставить тут DELETE. В дальнейшем в данный метод будут добавлены возможности feedBack по tip-у (нажал на крестик, нажал на tip и т.д.) - запланировано в релизе 2.1

____________

GET /selfservice/ctn/{ctn} - получение данных ТП
POST/selfservice/ctn/{ctn}/tps/mobile/{soc} - изменение данных ТП 

GET /selfservice/ctn/{ctn}/subscriptions - получение подписок абонента
DELETE /selfservice/ctn/{ctn}/subscriptions/{id} - отключение подписок

в обоих случаях принимается ctn, и в обоих случаях ctn идет на первом месте

**Comment by vani2** [comment]
Насчёт POST/DELETE ок.

Насчёт формата: REST предполагает формат entity/entityId. В запросах

> /selfservice/ctn/{ctn}
/selfservice/ctn/{ctn}/subscriptions/{id}

это правило выполняется (entity - ctn/subscriptions, entityId - {ctn}/{id}), а в tips получаем пропущенную entity - ctn, после tips идет {ctn} (ожидается {id}).

**Comment by SuperCuke** [comment]
Это нормальный url для ресурса. 

Если у вас есть **конкретное** обоснование почему вы не можете вызвать этот урл приведите его, тк сейчас мы не видим никаких проблем.
