### ISSUE TITLE
Использование query-параметров в POST-запросах

### ISSUE THREAD

**Issue by vani2** [Beeline-Digital/api.beeline.ru#8]
Это нарушение спецификации HTML4:
http://www.w3.org/TR/html4/interact/forms.html#submit-format
> post: With the HTTP "post" method, the form data set is included in the body of the form and sent to the processing agent.

**Comment by SuperCuke** [comment]
Не совсем понятно при чем здесь спецификация **html** при обсуждении API.
По спецификации **http** нет явных запретов передавать queryString в POST запросе

**Comment by vani2** [comment]
@SuperCuke ок, закрываю
