### ISSUE TITLE
Тип возвращаемых данных не универсальный

### ISSUE THREAD

**Issue by vani2** [Beeline-Digital/api.beeline.ru#9]
`GET/healthcheck/heartbeat` - возвращает string. В части запросах приходит массив, в других объект. При обновлении API будет нарушена обратная совместимость, с этой целью была  рекомендация данные в JSON-выдаче вкладывать в корневое свойство data.

Если метод возвращает примитив (число или строку), формат выдачи нельзя будет изменить без нарушения функционирования клиентов, использующих этот метод — они жёстко завязаны на топологию выдачи.
В случае, если выдача будет включать в себя словарь с ключом data внутри, её можно будет безболезненно расширять без боязни сломать интеграцию.

**Comment by SuperCuke** [comment]
GET/healthcheck/heartbeat - данный метод предназначен для администроров чтобы вызывать из автоматических систем и сделан в соответствии с их требованиями. 

Больше никаких потребителей у этого метода быть не должно. Непонятно о какой обратной совместимости в таком случае идет речь.
При обновлении API данный метод меняться не должен - он всегда будет возвращать OK или ошибку

**Comment by sashaozz** [comment]
@SuperCuke Видимо нужно скрыть этот метод из генерируемой публичной спецификации.

**Comment by vani2** [comment]
@SuperCuke про обратную совместимость - это про все методы в целом, не про heartbeat.

**Comment by SuperCuke** [comment]
Метод heartbeat не должен вызываться приложением. 
Мы уберем его из спецификации, чтобы вас это смущало.
Если у вас есть **конкретные** претензии к другим методам, заведите отдельный issue и подробно опишите суть проблемы

**Comment by vani2** [comment]
@SuperCuke насчет heartbeat я понял. Забудем про него. 

>  В части запросах приходит массив, в других объект. При обновлении API будет нарушена обратная совместимость, с этой целью была рекомендация данные в JSON-выдаче вкладывать в корневое свойство data.
> 
> В случае, если выдача будет включать в себя словарь с ключом data внутри, её можно будет безболезненно расширять без боязни сломать интеграцию.

Этот кусок актуален. Это относится ко всем методам в целом. Если вы готовы принимать риски и соглашаетесь, что методы API будут изменяться версионированием (/v1, /v2 и т.д.), то проблем не будет. Ежели мы в запросе, который сейчас возвращает массив, придется изменить выдачу на объект, старые версии мобильного приложения их не распарсят. Надеюсь, понятно объяснил.

**Comment by vani2** [comment]
Выяснили, что версионирование будет через поле заголовка.
